### ISSUE TITLE
cocoapods  didn't find LGSemiModalNavController

### ISSUE THREAD

**Issue by Yak0xff** [lukegeiger/LGSemiModalNavController#1]
[!] Unable to find a pod with name matching `LGSemiModalNavController'

**Comment by lukegeiger** [comment]
Hey @RobinChao not sure what this could be. I created a sample project and tried to replicate but I cant. It seems to be working just fine for me. Make sure you have the following

```
pod "LGSemiModalNavController"
```

Here is the pod on cocoapods.org https://cocoapods.org/?q=lgsemimodal

I edit podfiles in vi, and I know a few times when I tried editing them in some other text editor, it would act up a bit when it came to entering quotes. So I am assuming that is what is going on.

**Comment by lukegeiger** [comment]
Closing for now, feel free to reopen if you need more help.
