### ISSUE TITLE
Modified the keyboard dismiss page will have a dramatic rebound effect

### ISSUE THREAD

**Issue by LiuSky** [lukegeiger/LGSemiModalNavController#4]
Has been repaired

**Comment by lukegeiger** [comment]
@LiuSky you have to give me more information on what the issue is, I have no idea wha you are talking about.

**Comment by LiuSky** [comment]
Plus this sentence can solve my problem @lukegeiger 
<img width="580" alt="2015-09-11 12 02 08" src="https://cloud.githubusercontent.com/assets/3087745/9793535/7761defa-5818-11e5-9e2f-212b702982b0.png">
